feat: native apple silicon
ipfs/ipfs-desktop pull request #1856
Opened 2021-06-23 18:17 UTC by lidel

This is exploration into better support of Apple Silicon.

[electron-builder](https://github.com/electron-userland/electron-builder) supports producing either universal package or one for each architecture, but in our case gets tricky, because we also bundle go-ipfs binary. Unless the go-ipfs binary  is also universal or per-arch, we can't improve much.

2021-07-22 06:39 UTC, AlexxNica commented
@lidel, do we know where the difference in size comes from, specifically? We could find where they are and try something to minimize the impact of shipping the universal package.

2021-07-23 20:08 UTC, unbeatable-101 commented
> @lidel, do we know where the difference in size comes from, specifically? We could find where they are and try something to minimize the impact of shipping the universal package.

Not a dev, but I'm pretty sure the size increase is just the binaries about doubling in size due to basically containing two apps.

2021-09-22 10:47 UTC, jenkijo commented
Hello, any update?
I've committed fix for `go-ipfs` [https://github.com/ipfs/npm-go-ipfs/pull/43](https://github.com/ipfs/npm-go-ipfs/pull/43)

2021-09-28 04:52 UTC, dvcrn commented
Thanks for the PR! I wanted to build this locally but ran into issues with the build step trying to download a arm ipfs binary that obviously didn't exist. How did you build this?

2021-10-03 02:29 UTC, jenkijo commented
It work fine with me, what error that you got?

2022-03-24 11:43 UTC, hacdias commented
I think that Universal would be easier for the end users despite the storage size.

2022-05-06 16:26 UTC, SgtPooki commented
Have we looked into https://github.com/tauri-apps/tauri at all?

2022-05-06 18:33 UTC, SgtPooki commented
Regarding universal app vs rosetta specific.. the speed increases you get by running M1 native is significant. I don't think we should decide to just force rosetta forevermore. If the decision is to wait for some period until we have more bandwidth, I think sticking with rosetta and the smaller bundle for now is fine. Ultimately, we should be moving to the type of app bundle the platform we're targeting recommends. 

For Apple/macOS, that is the universal build.

2022-05-06 18:54 UTC, hacdias commented
@SgtPooki an issue you may want to look at too is #867

2022-05-16 12:29 UTC, lidel commented
> Have we looked into https://github.com/tauri-apps/tauri

I think we looked at it briefly, but it was very alpha back then.  IIRC the main downside was lack of tooling for end-to-end autoupdate solution, which is raison d'être of ipfs-desktop.  It seems they work on it, but it is still undocumented? https://github.com/tauri-apps/tauri/discussions/2776

Long term, we want to move away from fetching updates from centralized HTTP server like github and leverage IPFS+IPNS  instead (see old notes in https://github.com/ipfs/ipfs-desktop/issues/789), so if we have working setup for that, we could move away from Electron (literally the only value it brings is https://www.electron.build/auto-update working on all three platforms: macOS+Windows+Linux(AppImage))

>  75 MB won't probably affect many people.

Usually I would be against doubling the size of download, but we talk Apple here – it is fair to assume that  if someone uses mac they most likely don't care about additional download cost.

The caveat here is that we don't have "universal go-ipfs binary" – iiuc this PR (in current form) still bundles the intel version of go-ipfs.  

Figuring out how to include both binaries  (arm64 and amd64) for darwin  is the key to unblocking this.

2022-10-07 16:21 UTC, Whitedragon2772 commented
lo

2022-12-07 05:13 UTC, SgtPooki commented
> I wrote a plan for unblocking this in https://github.com/ipfs/distributions/issues/770#issuecomment-1329178981.
> 
> Not a macOS user myself, but if someone wants to work on this, I'm around to advise.

I read that comment and the approach seems reasonable and clear. Thanks for the backlink!

2023-07-07 23:55 UTC, lidel commented
There are two separate topics at play (mind I am not macOS user, below is my rough understanding on Apple Silicon situation)

- architecture of go binary (kubo daemon) 
  -  What we did on dist.ipfs.tech is we provide separate Kubo binaries for `amd64` (intel) and `arm64` (arm/apple silicon) (https://github.com/ipfs/distributions/pull/838, https://github.com/ipfs/distributions/pull/841). 
    - Brave downloads correct binary at runtime. 
    - There is no universal binary for Kubo, but you could build one as noted in https://github.com/ipfs/distributions/issues/770#issuecomment-1329178981 – afaik nobody is doing that atm.
      - IPFS Desktop DMG bundles NPM version pulled in during the build – afaik this is still amd64, so it runs emulation.
      - IPFS Desktop needs to either stop embeedding and fetch correct binary at runtime, or include both and run correct one on macOS. 
- architecture of electron app (ipfs desktop)
  - this feels unresolved, but maybe not a big deal, since the majority of work happens in kubo?
  -  iiuc what happens on macOS is that we produce DMG that is amd64 and when run on Apple Silicon it runs emulation


I agree we should close this, and if we want to use native arch on macOS, need to fill new issue and make a new plan for both topics above.

2023-10-18 19:52 UTC, SgtPooki commented
please see https://github.com/ipfs/ipfs-desktop/issues/2681 for a continuation of this work

2024-05-16 14:59 UTC, lidel commented
Reopening because of https://github.com/ipfs/ipfs-desktop/issues/2813

I will prototype Universal DMG that includes Universal Kubo binary as well.

2024-05-16 21:51 UTC, lidel commented
Fetching both `x86_64` `arm64` and merging them into universal Kubo binary is working ([build log](https://github.com/ipfs/ipfs-desktop/actions/runs/9119544018/job/25075202983#step:9:54)):

`→ lipo info after merging binaries
Architectures in the fat file: /Users/runner/work/ipfs-desktop/ipfs-desktop/node_modules/kubo/kubo/ipfs are: x86_64 arm64` 

Remaining work is to upstream [kubo+0.28.0.patch](https://github.com/ipfs/ipfs-desktop/blob/88396802ab76502e6becfead817893cb7fb13270/patches/kubo%2B0.28.0.patch) to [npm-kubo](https://github.com/ipfs/npm-kubo) repo and test DMG from this PR on both Intel and ARM macOS.

2024-05-17 09:36 UTC, 2color commented
Also tested Tested https://dweb.link/ipfs/bafybeidw62sobej3qlfsmxxw5bbnczz6ithimvixf3xg7rwquur3iww66q/ipfs-desktop-0.35.1-mac.dmg on ARM and it worked. Can test on a MacOS Intel tonight.

2024-06-10 21:08 UTC, SgtPooki requested changes
Should this be version `0.36.0`? code changes look fine. app shows universal. but I tried running the app ([from latest CI job](https://github.com/ipfs/ipfs-desktop/actions/runs/9454523632?pr=1856)) and it crashes immediately.

<img width="647" alt="image" src="https://github.com/ipfs/ipfs-desktop/assets/1173416/b6307a45-984f-42c8-a9c0-058201a5055f">


```
System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x0000007483f72aa9
Exception Codes:       0x0000000000000002, 0x0000007483f72aa9

Termination Reason:    Namespace SIGNAL, Code 10 Bus error: 10
Terminating Process:   exc handler [24263]

VM Region Info: 0x7483f72aa9 is in 0x74005c0000-0x7500000000;  bytes after start: 2207984297  bytes before end: 2080953686
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      Memory Tag 255             7400540000-74005c0000   [  512K] rw-/rwx SM=ZER  
--->  Memory Tag 255             74005c0000-7500000000   [  4.0G] ---/rwx SM=ZER  
      Memory Tag 255             7500000000-7500004000   [   16K] rw-/rwx SM=ZER  
```

2024-06-10 21:31 UTC, lidel commented
@SgtPooki yes, this will be released as 0.36.0 (2e891f3). 

The crash is concerning. 
- Are you on Intel or Apple Silicon machine?
- Is it crashing every time? 
- Was it crashing with RC 2 ([.zip of build here](https://github.com/ipfs/ipfs-desktop/actions/runs/9421878205/artifacts/1580337277))?

2024-06-10 23:22 UTC, SgtPooki commented
> * Are you on Intel or Apple Silicon machine?

Apple silicon

> * What is the version of macOS?

Sonoma 14.5 (23F79)

> * Is it crashing every time?

Yep.

> * Was it crashing with RC 2 ([.zip of build here](https://github.com/ipfs/ipfs-desktop/actions/runs/9421878205/artifacts/1580337277))?
> 
> I can get my hands on M1 macMini tomorrow, but having second data point would be useful.

that version is also crashing for me immediately. I remember a previous version you asked me to test a month ago or so worked fine. If that's the same one, it's not now and the problem is my system.

2024-06-10 23:40 UTC, SgtPooki approved these changes

2024-06-12 00:06 UTC, lidel commented on package.json
> +    "electron-updater": "^6.2.1",
:information_source:  This includes fix for `powershell.exe -NoProfile -NonInteractive` errors:
https://github.com/electron-userland/electron-builder/issues/7127#issuecomment-1991876763

2024-06-12 13:51 UTC, lidel commented
Thanks, sounds like it.

FWIW I've just tested both on M1 macMini and both work ok. Let's merge and ship.

If crashes of IPFS Desktop binary (electron) rather than kubo itself become common, then the first thing we should do is to upgrade to supported version of Electron (#2775)

2024-06-12 13:53 UTC, merged