fix: disable context isolation
ipfs/ipfs-desktop pull request #1894
Opened 2021-08-14 09:12 UTC by hacdias

Electron 12 introduced context isolation enabled by default. Thus, the
`window` object that the preload script and the Web UI page have access
to are different. Hence, Web UI cannot detect if it's running inside
Desktop. Disabling Cobtext Isolation fixes the issue.

## How can you see it is not working properly in the current version?

Open Settings, go to the Analytics part and check the events list. If you don't see `SCREENSHOT_TAKEN` (among others) is because of this.

License: MIT
Signed-off-by: Henrique Dias <hacdias@gmail.com>

2021-08-18 21:01 UTC, lidel requested changes
I am afraid of exposing powerful electron apis to the browser process– better to avoid this if we can, especially if it only impacts desktop detection and metrics, and has no impact on actual functionality.

Would it be possible to keep `contextIsolation: false` and use `contextBridge.exposeInMainWorld` instead  ([docs](https://www.electronjs.org/docs/tutorial/context-isolation#context-isolation)) ?

2021-08-19 06:53 UTC, hacdias commented
@lidel okay, I will implement this, but I will also be required to make a few other changes on the Web UI to make sure all integrations work.

2021-08-19 07:30 UTC, hacdias commented
@lidel updated to use `contextBridge`. I also added a function `updateLanguage` that will be explicitly called by Web UI when updating the language (see https://github.com/ipfs/ipfs-webui/pull/1839). This way we do not need to wrap the `localStorage.setItem`.

2021-09-01 21:34 UTC, lidel approved these changes
Perfect!  LGTM.

Let's merge this and https://github.com/ipfs/ipfs-webui/pull/1839. I'll bump webui version in desktop before release, so everything keeps working as expected.

2021-09-01 21:35 UTC, merged