docs: Add repo.lock troubleshooting steps to readme
ipfs/ipfs-desktop pull request #2111
Opened 2022-04-25 18:50 UTC by SgtPooki

repo.lock issues are frequent, and we don't have an easy place for users to find a solution for this. This PR should help.

2022-05-06 18:45 UTC, SgtPooki commented
@hacdias lidel should be back on Monday, but it would be nice to close some PRs on this repo if you get a chance to peek at this tiny PR.

2022-05-06 19:23 UTC, hacdias requested changes
Some small nitpicks and a link to the repository location information. I think we can merge this without @lidel's review as it is very small and just doc-related.

2022-05-06 19:23 UTC, hacdias commented on README.md
> +### I got a repo.lock error. How do I resolve this?
```suggestion
### I got a `repo.lock` error. How do I resolve this?
```

2022-05-06 19:23 UTC, hacdias commented on README.md
> +In general, this means that a previous process was unable to remove the repo lock (indicator that file is in use) from the repo file. This is supposed to be handled automatically, but sometimes it is
```suggestion
In general, this means that a previous process was unable to remove the repository lock (indicator that file is in use) from the repository directory. This is supposed to be handled automatically, but sometimes it isn't. If you get this error, you can generally safely delete this file after shutting down any running IPFS daemon's or applications. Simple process is as follows:
```

2022-05-06 19:23 UTC, hacdias commented on README.md
> +2. Manually delete lock file
```suggestion
2. Manually delete lock file, located within the [repository](#how-does-ipfs-desktop-select-the-ipfs-repo-location)
```

2022-05-06 19:23 UTC, hacdias commented on README.md
> +3. Attempt to start ipfs desktop (or other process that received the repo.lock error) again.
```suggestion
3. Attempt to start ipfs desktop (or other process that received the `repo.lock` error) again.
```

2022-05-09 16:08 UTC, SgtPooki commented on README.md
> +2. Manually delete lock file
ooh nice.

2022-05-09 16:09 UTC, SgtPooki commented
Thanks @hacdias ! I used all your suggestions =)

2022-05-09 20:57 UTC, hacdias approved these changes

2022-05-10 12:37 UTC, merged