feat:  default MFS to CIDv1
ipfs/ipfs-desktop pull request #2527
Opened 2023-06-22 05:37 UTC by whizzzkid

Fixes: #2361

2024-07-16 21:14 UTC, rtxs34 approved these changes

2024-11-08 00:01 UTC, lidel requested changes

2024-11-11 19:29 UTC, SgtPooki commented on src/enable-cid-v1.js
> +      await ipfsd.api.files.chcid('/', { cidVersion: 1 })
i'd much rather just pull in settings directly from kubo and have things work there if we can

2024-11-13 13:56 UTC, lidel commented on src/enable-cid-v1.js
> +      await ipfsd.api.files.chcid('/', { cidVersion: 1 })
Yes, I think we need a fix in Kubo. It should respect `Import.*`  especially `Import.CidVersion` when a new MFS root is created.  (TODO: fill issue once im at PC)

2025-03-10 15:08 UTC, 2color commented on src/enable-cid-v1.js
> +      await ipfsd.api.files.chcid('/', { cidVersion: 1 })
@lidel Did you end up opening an issue for this?

2026-04-28 18:18 UTC, lidel commented on src/enable-cid-v1.js
> +      await ipfsd.api.files.chcid('/', { cidVersion: 1 })
Relevant Import.* + MFS fixes shipped in Kubo 0.41

2026-04-28 18:19 UTC, lidel commented
Superseded by #3132 and switch by default is tracked in #2361

2026-04-28 18:19 UTC, closed without merging